export const DEPARTMENTS = [
  'Financeiro',
  'Contábil / Fiscal',
  'Comercial',
  'Tecnologia da Informação',
  'Recursos Humanos',
  'Limpeza',
  'Operações I',
  'Operações II',
  'Operações III',
  'Expedição I',
  'Expedição II',
  'Expedição III',
  'Solda / Montagem I',
  'Solda / Montagem II',
  'Solda / Montagem III',
  'Logistica Administrativa',
  'Compras / Recebimento',
  'Almoxarifado',
  'Logistica Transportes',
  'Portaria',
  'Diretoria',
  'Manutenção',
]
